name: pibi25
channels:
  - defaults
dependencies:
  - python==3.12
  - jupyter
  - nbgrader
  - numpy
  - pandas
  - scikit-learn
  - seaborn
  - biopython
  - statsmodels 
  - openpyxl
  - plotly
  - reportlab
  - dtreeviz
